{{- if .Values.keycloak.enabled -}}
# apenas para h2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end -}}
