{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vkpr.serviceAccountName" . }}
  labels:
{{ include "vkpr.labels" . | nindent 4 }}
{{- end -}}
