#
# Valores para testes locais com o k3d.
# 
# O que executa:
# - Ingress controller (ingress-nginx)
# - Aplicação "whoami"
# - Keycloak
#
# INSTALAÇÃO COM MAKEFILE:
#
# make k3d_create
# make example_local_keycloak
#
#
# INSTALAÇÃO VIA HELM (manual):
#
# kubectl create secret generic vkpr-realm-secret --from-file=examples/keycloak/realms/realm.json
# helm upgrade -i vkpr -f examples/local/values-local-keycloak.yaml ./charts/vkpr
#
# Coloque as seguintes entradas no /etc/hosts :
# 127.0.0.1    keycloak.localdomain
#
# Abrir a seguinte URL no browser:
#
# http://localhost:5443/
#

#
# INGRESS STACK
#
ingress-nginx:
  enabled: true

external-dns:
  enabled: false
cert-manager:
  enabled: false

# chart values
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
  - host: whoami.localdomain
    paths: ["/"]

#
# LOGGING STACK:
#

loki-stack:
  enabled: false

#
# MONITORING STACK
#
kube-prometheus-stack:
  enabled: false

#
# SECURITY STACK
#
vault:
  enabled: false

keycloak:
  enabled: true
  rbac:
    create: true
  postgresql:
    enabled: false
  ingress:
    enabled: true
    tls: []
    annotations:
      kubernetes.io/ingress.class: nginx
    rules:
      - host: "keycloak.localdomain"
        paths: ["/"]
  # mounts realm.json as secret
  # mounts volume as H2 database (when no postgres is used)
  extraVolumes: |
    - name: vkpr-realm-secret
      secret:
        secretName: vkpr-realm-secret
    - name: keycloak-data
      persistentVolumeClaim:
        claimName: keycloak-data-volume
  extraVolumeMounts: |
    - name: vkpr-realm-secret
      mountPath: "/realm/"
      readOnly: true
    - name: keycloak-data
      mountPath: "/opt/jboss/keycloak/standalone/data"
      readOnly: false
  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: vert1234
