nginx-ingress:
  enabled: false
  controller:
    publishService:
      enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3

external-dns:
  enabled: false

cert-manager:
  enabled: false

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: whoami.<DOMAIN_NAME>
      paths: ["/"]

prometheus-operator:
  enabled: true
  grafana:
    adminPassword: "vertigo"

velero:
  enabled: false
